@extends('layouts.front')
@section('content')
<section class="vds-main">
	<div class="container">
		<div class="vidz_sec">
			<span class="page-title"><i class="fas fa-user-lock"></i> Privacy Policy</span>
			<div class="vidz_list">
				<div class="row">
					
				</div>
			</div>
		</div>					
		<div class="form-separation"></div>
		<div class="vidz_list">
			<div style="width:100%;text-align:justify;">
				<p>
					Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Turpis egestas integer eget aliquet nibh praesent tristique magna. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Velit laoreet id donec ultrices tincidunt arcu. Volutpat maecenas volutpat blandit aliquam. Sed viverra ipsum nunc aliquet. Morbi tincidunt augue interdum velit euismod in pellentesque. Pharetra diam sit amet nisl. Varius duis at consectetur lorem. Enim nunc faucibus a pellentesque sit amet porttitor. Odio euismod lacinia at quis risus. Bibendum est ultricies integer quis auctor elit sed. Ut sem nulla pharetra diam sit amet. Nam aliquam sem et tortor consequat. Amet consectetur adipiscing elit duis tristique sollicitudin. Nisi vitae suscipit tellus mauris a diam maecenas. Sagittis purus sit amet volutpat consequat mauris nunc congue. Est ultricies integer quis auctor elit sed vulputate mi sit. Consequat id porta nibh venenatis cras sed felis eget.
					
					Dolor purus non enim praesent elementum facilisis leo vel. Purus in massa tempor nec feugiat. Maecenas accumsan lacus vel facilisis volutpat est velit egestas. Bibendum neque egestas congue quisque egestas diam in. Et malesuada fames ac turpis egestas maecenas pharetra convallis. Egestas tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Et malesuada fames ac turpis. Quisque non tellus orci ac auctor augue mauris augue. Lorem donec massa sapien faucibus et molestie ac. Neque aliquam vestibulum morbi blandit cursus risus at. Fermentum leo vel orci porta non pulvinar neque laoreet suspendisse. Mauris nunc congue nisi vitae suscipit tellus mauris. Adipiscing diam donec adipiscing tristique risus. Nulla porttitor massa id neque aliquam vestibulum. Diam quam nulla porttitor massa id neque. Faucibus a pellentesque sit amet. Ultrices gravida dictum fusce ut placerat orci. Ridiculus mus mauris vitae ultricies leo. Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum sociis.
					
					A lacus vestibulum sed arcu non odio euismod lacinia. Sapien et ligula ullamcorper malesuada proin libero nunc consequat. Ultricies mi eget mauris pharetra et. Faucibus vitae aliquet nec ullamcorper. Magna sit amet purus gravida quis. Felis eget velit aliquet sagittis id consectetur. Amet est placerat in egestas erat imperdiet sed euismod. Commodo ullamcorper a lacus vestibulum. Pellentesque massa placerat duis ultricies. Congue eu consequat ac felis donec et odio pellentesque. Erat nam at lectus urna duis convallis.
					
					Neque viverra justo nec ultrices dui sapien eget mi. Laoreet id donec ultrices tincidunt. Hendrerit gravida rutrum quisque non tellus orci ac auctor augue. Lacus suspendisse faucibus interdum posuere. Sed tempus urna et pharetra pharetra massa massa ultricies. Pulvinar mattis nunc sed blandit. Viverra vitae congue eu consequat ac. Egestas egestas fringilla phasellus faucibus scelerisque eleifend. Amet purus gravida quis blandit turpis cursus. Malesuada proin libero nunc consequat interdum varius sit amet. Neque gravida in fermentum et sollicitudin. Eu non diam phasellus vestibulum lorem. Nunc id cursus metus aliquam eleifend mi. Amet consectetur adipiscing elit ut aliquam purus. Sed cras ornare arcu dui vivamus arcu. In mollis nunc sed id semper risus in. Semper risus in hendrerit gravida rutrum quisque non. Tempus iaculis urna id volutpat. Vitae aliquet nec ullamcorper sit amet risus. Eu volutpat odio facilisis mauris.
					
					Mus mauris vitae ultricies leo integer malesuada. Vitae justo eget magna fermentum iaculis eu non diam phasellus. Amet consectetur adipiscing elit pellentesque habitant. Erat imperdiet sed euismod nisi porta lorem mollis. Diam quis enim lobortis scelerisque fermentum dui faucibus. Fusce id velit ut tortor pretium viverra suspendisse. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Risus nec feugiat in fermentum posuere urna nec tincidunt praesent. Egestas maecenas pharetra convallis posuere morbi leo. Enim eu turpis egestas pretium aenean pharetra.
					
					Placerat vestibulum lectus mauris ultrices eros. Et tortor consequat id porta. Molestie a iaculis at erat pellentesque adipiscing. Duis ultricies lacus sed turpis tincidunt id aliquet. Lacinia quis vel eros donec ac odio tempor orci. Euismod quis viverra nibh cras pulvinar mattis nunc sed blandit. Enim facilisis gravida neque convallis. Diam phasellus vestibulum lorem sed. Id eu nisl nunc mi ipsum faucibus vitae. Elit ut aliquam purus sit amet luctus venenatis. Donec adipiscing tristique risus nec feugiat in fermentum posuere urna. Vel orci porta non pulvinar neque laoreet. Sem et tortor consequat id porta nibh venenatis cras. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies. Facilisi etiam dignissim diam quis. Bibendum ut tristique et egestas quis. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan. Purus viverra accumsan in nisl nisi scelerisque eu ultrices vitae.
					
					Cum sociis natoque penatibus et magnis dis. Velit aliquet sagittis id consectetur. Cursus risus at ultrices mi tempus imperdiet nulla malesuada. Augue ut lectus arcu bibendum at varius vel. Consequat id porta nibh venenatis cras sed felis eget. Et tortor consequat id porta. Ipsum faucibus vitae aliquet nec. Etiam dignissim diam quis enim lobortis. Placerat in egestas erat imperdiet sed. Congue nisi vitae suscipit tellus mauris a diam maecenas. Aliquam malesuada bibendum arcu vitae elementum curabitur vitae nunc sed. Eleifend quam adipiscing vitae proin sagittis nisl rhoncus mattis. Egestas sed sed risus pretium quam. Posuere sollicitudin aliquam ultrices sagittis orci a. Sem fringilla ut morbi tincidunt augue interdum velit. Semper auctor neque vitae tempus quam pellentesque nec. Habitasse platea dictumst quisque sagittis purus sit amet volutpat consequat. Mi ipsum faucibus vitae aliquet. Aenean euismod elementum nisi quis eleifend quam.
					
					Ipsum dolor sit amet consectetur. Ullamcorper a lacus vestibulum sed. In ornare quam viverra orci sagittis. Ut sem viverra aliquet eget. Ultricies mi eget mauris pharetra et. Tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada. Sagittis purus sit amet volutpat consequat mauris nunc. Praesent semper feugiat nibh sed pulvinar. A erat nam at lectus urna duis convallis convallis. Tellus id interdum velit laoreet id donec. Lobortis scelerisque fermentum dui faucibus in. Turpis egestas integer eget aliquet nibh praesent tristique magna. Et ultrices neque ornare aenean euismod elementum nisi quis eleifend. Non tellus orci ac auctor augue mauris augue neque. Magna ac placerat vestibulum lectus. Sit amet volutpat consequat mauris nunc congue nisi vitae. Nunc sed velit dignissim sodales ut eu sem integer.
					
					Enim ut sem viverra aliquet. Facilisis leo vel fringilla est ullamcorper eget. Metus vulputate eu scelerisque felis imperdiet proin fermentum leo. Aliquet sagittis id consectetur purus ut faucibus pulvinar elementum integer. Sit amet mauris commodo quis. Justo laoreet sit amet cursus sit amet dictum sit. Vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras. Sagittis eu volutpat odio facilisis mauris sit amet massa. Malesuada fames ac turpis egestas sed tempus. Libero enim sed faucibus turpis in eu mi bibendum neque. Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum. Potenti nullam ac tortor vitae. Suspendisse sed nisi lacus sed viverra tellus in. Cursus vitae congue mauris rhoncus aenean vel elit. In hac habitasse platea dictumst vestibulum rhoncus. Elit duis tristique sollicitudin nibh sit amet commodo. Mollis nunc sed id semper. Elementum nibh tellus molestie nunc. Libero enim sed faucibus turpis in eu mi bibendum. Eu mi bibendum neque egestas.
					
					Risus quis varius quam quisque id diam vel quam. Et malesuada fames ac turpis egestas. Dictum sit amet justo donec enim diam vulputate ut pharetra. Mi proin sed libero enim sed faucibus turpis in eu. Ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Molestie nunc non blandit massa enim. Blandit cursus risus at ultrices mi tempus imperdiet nulla. Cras sed felis eget velit aliquet. Nunc faucibus a pellentesque sit amet porttitor eget dolor. Arcu non sodales neque sodales ut etiam sit. Vitae congue eu consequat ac felis donec et odio. Nibh tellus molestie nunc non blandit massa. Mattis nunc sed blandit libero volutpat sed cras. Amet volutpat consequat mauris nunc. Gravida rutrum quisque non tellus orci ac auctor. Nisl purus in mollis nunc sed id semper. Odio ut enim blandit volutpat maecenas volutpat blandit aliquam.
					
					Ut sem viverra aliquet eget sit amet tellus. Sodales neque sodales ut etiam sit amet nisl purus. Laoreet suspendisse interdum consectetur libero id faucibus. Tellus elementum sagittis vitae et leo duis. Lacus viverra vitae congue eu consequat ac. Purus semper eget duis at tellus at. Pretium aenean pharetra magna ac. Maecenas sed enim ut sem viverra aliquet eget sit amet. Netus et malesuada fames ac turpis egestas sed. Condimentum vitae sapien pellentesque habitant morbi tristique senectus. Duis at consectetur lorem donec massa sapien. Vel pharetra vel turpis nunc eget lorem dolor.
					
					Sapien eget mi proin sed libero enim sed faucibus. Orci porta non pulvinar neque. Cras sed felis eget velit aliquet sagittis id consectetur purus. Ultricies leo integer malesuada nunc vel risus. Nulla posuere sollicitudin aliquam ultrices sagittis orci a. Sed turpis tincidunt id aliquet risus. Pharetra diam sit amet nisl. Amet porttitor eget dolor morbi. Risus commodo viverra maecenas accumsan lacus vel facilisis. Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum.
					
					Vitae elementum curabitur vitae nunc sed velit dignissim sodales. Amet est placerat in egestas erat imperdiet sed. Ut pharetra sit amet aliquam id diam. Sed augue lacus viverra vitae. Dictumst quisque sagittis purus sit amet volutpat consequat mauris. Eget est lorem ipsum dolor. Nam at lectus urna duis convallis. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras. Eleifend mi in nulla posuere. Morbi tincidunt augue interdum velit euismod. Eu facilisis sed odio morbi. Pellentesque adipiscing commodo elit at imperdiet. Tristique senectus et netus et malesuada fames ac turpis. Auctor elit sed vulputate mi sit amet mauris commodo quis. Id aliquet risus feugiat in ante metus. Ut tortor pretium viverra suspendisse potenti nullam ac. Blandit volutpat maecenas volutpat blandit aliquam. Aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Enim nunc faucibus a pellentesque sit. Dui nunc mattis enim ut tellus.
					
					Vel turpis nunc eget lorem dolor sed viverra. Amet risus nullam eget felis eget nunc. Aliquet porttitor lacus luctus accumsan tortor posuere ac ut consequat. Urna condimentum mattis pellentesque id nibh. In egestas erat imperdiet sed euismod. Sapien eget mi proin sed libero enim sed faucibus. Mi sit amet mauris commodo quis imperdiet. Turpis egestas integer eget aliquet nibh praesent tristique magna sit. Congue eu consequat ac felis donec. Condimentum vitae sapien pellentesque habitant morbi tristique. Est velit egestas dui id ornare arcu odio ut sem. Pellentesque nec nam aliquam sem et tortor consequat id. At imperdiet dui accumsan sit amet nulla facilisi morbi tempus. Velit scelerisque in dictum non consectetur a. Viverra aliquet eget sit amet tellus cras. Quis ipsum suspendisse ultrices gravida dictum. Pulvinar etiam non quam lacus suspendisse faucibus interdum posuere. Id ornare arcu odio ut sem. Ipsum suspendisse ultrices gravida dictum fusce ut placerat orci.
					
					Donec massa sapien faucibus et. Elementum eu facilisis sed odio morbi quis commodo odio. Cursus metus aliquam eleifend mi. Nunc sed blandit libero volutpat sed cras ornare. Tortor aliquam nulla facilisi cras. Condimentum id venenatis a condimentum vitae sapien pellentesque. In nibh mauris cursus mattis molestie a. Faucibus purus in massa tempor. Dolor sit amet consectetur adipiscing elit duis. Aliquam ut porttitor leo a diam. Ac ut consequat semper viverra nam libero justo laoreet. In eu mi bibendum neque egestas congue quisque egestas diam. Leo integer malesuada nunc vel risus commodo viverra maecenas. Fermentum iaculis eu non diam phasellus.
					
					Netus et malesuada fames ac. Proin libero nunc consequat interdum varius sit amet. Sit amet consectetur adipiscing elit. Varius vel pharetra vel turpis nunc eget lorem dolor sed. Faucibus in ornare quam viverra orci sagittis eu volutpat. Vulputate odio ut enim blandit volutpat. Sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur. Tortor at auctor urna nunc. Ac tortor dignissim convallis aenean et tortor at risus. Nunc id cursus metus aliquam eleifend mi in nulla posuere. Odio morbi quis commodo odio aenean sed adipiscing diam.
					
					Gravida in fermentum et sollicitudin ac. Ac ut consequat semper viverra. Et malesuada fames ac turpis. Non arcu risus quis varius quam quisque. Ultricies leo integer malesuada nunc vel risus commodo viverra maecenas. Leo urna molestie at elementum eu facilisis sed odio. Nisl tincidunt eget nullam non nisi est sit amet. Eros donec ac odio tempor. Aliquam purus sit amet luctus venenatis lectus. Dolor sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Sed velit dignissim sodales ut eu sem integer. Tristique senectus et netus et malesuada fames ac turpis egestas. Vitae congue eu consequat ac felis donec et. Ac ut consequat semper viverra. Pellentesque habitant morbi tristique senectus et netus et malesuada.
					
					Mi eget mauris pharetra et ultrices neque. Tellus orci ac auctor augue mauris augue. Est sit amet facilisis magna. Convallis posuere morbi leo urna molestie at elementum. Massa id neque aliquam vestibulum morbi blandit cursus. Urna condimentum mattis pellentesque id nibh tortor id aliquet lectus. Viverra tellus in hac habitasse platea dictumst vestibulum rhoncus est. Nulla aliquet enim tortor at. Vel facilisis volutpat est velit egestas dui id. Nam libero justo laoreet sit amet. Et netus et malesuada fames ac turpis. Diam phasellus vestibulum lorem sed risus ultricies tristique nulla. Vel turpis nunc eget lorem dolor sed viverra ipsum. Massa id neque aliquam vestibulum morbi blandit cursus risus at. Bibendum arcu vitae elementum curabitur vitae.
					
					Tortor id aliquet lectus proin nibh nisl condimentum. Sed tempus urna et pharetra pharetra. Integer eget aliquet nibh praesent tristique. Quis lectus nulla at volutpat diam ut. Ut etiam sit amet nisl. Duis ut diam quam nulla porttitor. In dictum non consectetur a erat. Nunc id cursus metus aliquam eleifend mi. Risus nullam eget felis eget. Mauris ultrices eros in cursus turpis massa tincidunt. Vulputate enim nulla aliquet porttitor lacus. Sit amet nisl purus in mollis nunc. Morbi tempus iaculis urna id volutpat lacus laoreet non curabitur. Id aliquet risus feugiat in. Orci phasellus egestas tellus rutrum tellus pellentesque eu. Vulputate sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum.
					
					Condimentum vitae sapien pellentesque habitant. Est ante in nibh mauris cursus mattis molestie a iaculis. Ullamcorper morbi tincidunt ornare massa eget egestas purus. Ut aliquam purus sit amet luctus venenatis. Orci ac auctor augue mauris. Ut ornare lectus sit amet est placerat in. Odio pellentesque diam volutpat commodo sed. Purus gravida quis blandit turpis. Quam vulputate dignissim suspendisse in est. Vel fringilla est ullamcorper eget. Pharetra magna ac placerat vestibulum lectus mauris ultrices eros. Penatibus et magnis dis parturient montes nascetur ridiculus mus mauris. Morbi non arcu risus quis varius quam quisque. Quisque id diam vel quam elementum pulvinar etiam non quam. Mauris in aliquam sem fringilla ut morbi tincidunt.
				</p>
			</div>
		</div>
	</div>
</section><!--services-sec end-->
@endsection